export const CITIES: string[] = [
  // Pennsylvania (home base)
  "Pittsburgh, PA",
  "Philadelphia, PA",
  "Allentown, PA",
  "Erie, PA",
  "Reading, PA",
  "Scranton, PA",
  "Bethlehem, PA",
  "Lancaster, PA",
  "Harrisburg, PA",
  "York, PA",
  "Altoona, PA",
  "Wilkes-Barre, PA",
  "Chester, PA",
  "Easton, PA",
  "Monroeville, PA",
  "McKeesport, PA",
  "New Castle, PA",
  "Johnstown, PA",
  "State College, PA",
  "Bethel Park, PA",

  // Major US Cities
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "Columbus, OH",
  "Charlotte, NC",
  "Indianapolis, IN",
  "San Francisco, CA",
  "Seattle, WA",
  "Denver, CO",
  "Nashville, TN",
  "Oklahoma City, OK",
  "El Paso, TX",
  "Washington, DC",
  "Las Vegas, NV",
  "Louisville, KY",
  "Memphis, TN",
  "Portland, OR",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Mesa, AZ",
  "Kansas City, MO",
  "Atlanta, GA",
  "Omaha, NE",
  "Colorado Springs, CO",
  "Raleigh, NC",
  "Miami, FL",
  "Long Beach, CA",
  "Virginia Beach, VA",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tampa, FL",
  "Tulsa, OK",
  "Arlington, TX",
  "New Orleans, LA",
  "Wichita, KS",
  "Cleveland, OH",
  "Bakersfield, CA",
  "Aurora, CO",
  "Anaheim, CA",
  "Honolulu, HI",
  "Santa Ana, CA",
  "Corpus Christi, TX",
  "Riverside, CA",
  "Lexington, KY",
  "St. Louis, MO",
  "Stockton, CA",
  "St. Paul, MN",
  "Cincinnati, OH",
  "Anchorage, AK",
  "Greensboro, NC",
  "Plano, TX",
  "Newark, NJ",
  "Henderson, NV",
  "Lincoln, NE",
  "Buffalo, NY",
  "Fort Wayne, IN",
  "Jersey City, NJ",
  "Chula Vista, CA",
  "Orlando, FL",
  "St. Petersburg, FL",
  "Norfolk, VA",
  "Chandler, AZ",
  "Laredo, TX",
  "Madison, WI",
  "Durham, NC",
  "Lubbock, TX",
  "Winston-Salem, NC",
  "Garland, TX",
  "Glendale, AZ",
  "Hialeah, FL",
  "Reno, NV",
  "Baton Rouge, LA",
  "Irvine, CA",
  "Chesapeake, VA",
  "Scottsdale, AZ",
  "North Las Vegas, NV",
  "Fremont, CA",
  "Gilbert, AZ",
  "San Bernardino, CA",
  "Birmingham, AL",
  "Boise, ID",
  "Rochester, NY",
  "Richmond, VA",
  "Spokane, WA",
  "Des Moines, IA",
  "Montgomery, AL",
  "Modesto, CA",
  "Fayetteville, NC",
  "Tacoma, WA",
  "Akron, OH",
  "Shreveport, LA",
  "Aurora, IL",
  "Little Rock, AR",
  "Knoxville, TN",
  "Salt Lake City, UT",
  "Huntington Beach, CA",
  "Grand Rapids, MI",
  "Tallahassee, FL",
  "Worcester, MA",
  "Providence, RI",
  "Garden Grove, CA",
  "Oceanside, CA",
  "Fort Lauderdale, FL",
  "Tempe, AZ",
  "Jackson, MS",
  "Cape Coral, FL",
  "Moreno Valley, CA",
  "Glendale, CA",
  "Columbus, GA",
  "Alexandria, VA",
  "Savannah, GA",
  "Huntsville, AL",
  "Lakewood, CO",
  "Springfield, MO",
  "Pomona, CA",
  "Escondido, CA",
  "Syracuse, NY",
  "Sunnyvale, CA",
  "Kansas City, KS",
  "Rockford, IL",
  "Torrance, CA",
  "Paterson, NJ",
  "Bridgeport, CT",
  "Hartford, CT",
  "New Haven, CT",
  "Boston, MA",
  "Detroit, MI",
  "Portland, ME",
  "Burlington, VT",
  "Concord, NH",
  "Manchester, NH",
  "Fargo, ND",
  "Sioux Falls, SD",
  "Billings, MT",
  "Bozeman, MT",
  "Missoula, MT",
  "Charleston, WV",
  "Morgantown, WV",
  "Greenville, SC",
  "Columbia, SC",
  "Charleston, SC",
  "Wilmington, NC",
  "Asheville, NC",
  "Augusta, GA",
  "Macon, GA",
  "Chattanooga, TN",
  "Clarksville, TN",
  "Murfreesboro, TN",
  "Bowling Green, KY",
  "Covington, KY",
  "Dayton, OH",
  "Toledo, OH",
  "Canton, OH",
  "Youngstown, OH",
  "South Bend, IN",
  "Evansville, IN",
  "Bloomington, IN",
  "Ann Arbor, MI",
  "Lansing, MI",
  "Flint, MI",
  "Dearborn, MI",
  "Warren, MI",
  "Sterling Heights, MI",
  "Green Bay, WI",
  "Appleton, WI",
  "Racine, WI",
  "Kenosha, WI",
  "Springfield, IL",
  "Champaign, IL",
  "Quad Cities, IL",
  "Cedar Rapids, IA",
  "Davenport, IA",
  "Sioux City, IA",
  "Overland Park, KS",
  "Topeka, KS",
  "Wichita Falls, TX",
  "Abilene, TX",
  "Amarillo, TX",
  "Beaumont, TX",
  "McAllen, TX",
  "Killeen, TX",
  "Pueblo, CO",
  "Fort Collins, CO",
  "Boulder, CO",
  "Provo, UT",
  "Ogden, UT",
  "St. George, UT",
  "Henderson, NV",
  "Sparks, NV",
  "Flagstaff, AZ",
  "Yuma, AZ",
  "Surprise, AZ",
  "Peoria, AZ",
  "Eugene, OR",
  "Salem, OR",
  "Gresham, OR",
  "Bend, OR",
  "Medford, OR",
  "Bellevue, WA",
  "Everett, WA",
  "Kent, WA",
  "Yakima, WA",
  "Bellingham, WA",
  "Olympia, WA",
  "Spokane Valley, WA",
  "Bakersfield, CA",
  "Oxnard, CA",
  "Santa Rosa, CA",
  "Hayward, CA",
  "Lancaster, CA",
  "Palmdale, CA",
  "Salinas, CA",
  "Visalia, CA",
  "Santa Clarita, CA",
  "Pomona, CA",
  "Pasadena, CA",
  "Ontario, CA",
  "Rancho Cucamonga, CA",
  "Elk Grove, CA",
  "Corona, CA",
  "Murrieta, CA",
  "Temecula, CA",
  "Santa Clara, CA",
  "Roseville, CA",
  "Concord, CA",
  "Thousand Oaks, CA",
  "Simi Valley, CA",
  "Vallejo, CA",
  "Palmdale, CA",

  // Canada
  "Toronto, ON",
  "Montreal, QC",
  "Vancouver, BC",
  "Calgary, AB",
  "Edmonton, AB",
  "Ottawa, ON",
  "Winnipeg, MB",
  "Quebec City, QC",
  "Hamilton, ON",
  "Brampton, ON",
  "Mississauga, ON",
  "Surrey, BC",
  "Laval, QC",
  "Halifax, NS",
  "London, ON",
  "Markham, ON",
  "Vaughan, ON",
  "Gatineau, QC",
  "Saskatoon, SK",
  "Longueuil, QC",
  "Burnaby, BC",
  "Regina, SK",
  "Richmond, BC",
  "Richmond Hill, ON",
  "Oakville, ON",
  "Burlington, ON",
  "Windsor, ON",
  "Oshawa, ON",
  "Kitchener, ON",
  "Victoria, BC",

  // UK & Ireland
  "London, UK",
  "Manchester, UK",
  "Birmingham, UK",
  "Glasgow, UK",
  "Liverpool, UK",
  "Bristol, UK",
  "Edinburgh, UK",
  "Leeds, UK",
  "Sheffield, UK",
  "Cardiff, UK",
  "Belfast, UK",
  "Dublin, Ireland",
  "Cork, Ireland",
  "Galway, Ireland",

  // Europe
  "Paris, France",
  "Berlin, Germany",
  "Madrid, Spain",
  "Rome, Italy",
  "Amsterdam, Netherlands",
  "Brussels, Belgium",
  "Vienna, Austria",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Stockholm, Sweden",
  "Oslo, Norway",
  "Copenhagen, Denmark",
  "Helsinki, Finland",
  "Warsaw, Poland",
  "Prague, Czech Republic",
  "Budapest, Hungary",
  "Bucharest, Romania",
  "Athens, Greece",
  "Lisbon, Portugal",
  "Barcelona, Spain",
  "Munich, Germany",
  "Hamburg, Germany",
  "Frankfurt, Germany",
  "Cologne, Germany",
  "Milan, Italy",
  "Naples, Italy",
  "Turin, Italy",
  "Rotterdam, Netherlands",
  "Antwerp, Belgium",
  "Kyiv, Ukraine",
  "Kharkiv, Ukraine",
  "Minsk, Belarus",
  "Bern, Switzerland",

  // Caribbean & Latin America
  "Kingston, Jamaica",
  "Port of Spain, Trinidad",
  "Nassau, Bahamas",
  "Bridgetown, Barbados",
  "Santo Domingo, Dominican Republic",
  "San Juan, Puerto Rico",
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Bogotá, Colombia",
  "Medellín, Colombia",
  "Lima, Peru",
  "Santiago, Chile",
  "Buenos Aires, Argentina",
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Caracas, Venezuela",
  "Havana, Cuba",
  "Panama City, Panama",
  "San José, Costa Rica",
  "Guatemala City, Guatemala",

  // Africa
  "Lagos, Nigeria",
  "Abuja, Nigeria",
  "Accra, Ghana",
  "Nairobi, Kenya",
  "Johannesburg, South Africa",
  "Cape Town, South Africa",
  "Durban, South Africa",
  "Cairo, Egypt",
  "Addis Ababa, Ethiopia",
  "Dar es Salaam, Tanzania",
  "Kinshasa, DR Congo",
  "Casablanca, Morocco",
  "Tunis, Tunisia",
  "Algiers, Algeria",
  "Dakar, Senegal",

  // Middle East
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Doha, Qatar",
  "Kuwait City, Kuwait",
  "Manama, Bahrain",
  "Muscat, Oman",
  "Amman, Jordan",
  "Beirut, Lebanon",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Istanbul, Turkey",
  "Ankara, Turkey",
  "Tehran, Iran",
  "Baghdad, Iraq",

  // Asia
  "Tokyo, Japan",
  "Osaka, Japan",
  "Kyoto, Japan",
  "Sapporo, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Guangzhou, China",
  "Shenzhen, China",
  "Chengdu, China",
  "Wuhan, China",
  "Hong Kong",
  "Macau",
  "Taipei, Taiwan",
  "Singapore",
  "Bangkok, Thailand",
  "Chiang Mai, Thailand",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Jakarta, Indonesia",
  "Surabaya, Indonesia",
  "Kuala Lumpur, Malaysia",
  "Manila, Philippines",
  "Cebu, Philippines",
  "Yangon, Myanmar",
  "Phnom Penh, Cambodia",
  "Vientiane, Laos",
  "Dhaka, Bangladesh",
  "Karachi, Pakistan",
  "Lahore, Pakistan",
  "Islamabad, Pakistan",
  "Mumbai, India",
  "Delhi, India",
  "Bangalore, India",
  "Hyderabad, India",
  "Chennai, India",
  "Kolkata, India",
  "Pune, India",
  "Ahmedabad, India",
  "Kathmandu, Nepal",
  "Colombo, Sri Lanka",

  // Australia & New Zealand
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Gold Coast, Australia",
  "Newcastle, Australia",
  "Canberra, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",
];
